### ISSUE TITLE
🐛 Bug Report — node:util#inherits implementation breaks with `jws`/`jswebtoken` npm packages

### ISSUE THREAD

**Issue by IgorMinar** [cloudflare/workerd#2257] opened 2024-06-11 20:45 UTC
Repro:

- wrangler@3.60.2
- `compat_flags = ["experimental:nodejs_compat_v2"]`
- install and use `jws`https://www.npmjs.com/package/jws (or use `https://www.npmjs.com/package/jsonwebtoken` which uses jws`)

Expected: it works

Actual:

```
 Uncaught TypeError: The "superCtor.prototype" property must be of type object. Received undefined
    at null.<anonymous> (node:util:106:15) in inherits
    at null.<anonymous>
  (.../node_modules/jws/lib/data-stream.js:39:6) in
  node_modules/jws/lib/data-stream.js
    at null.<anonymous> (index.js:12:50) in __require
    at null.<anonymous>
  (.../node_modules/jws/lib/sign-stream.js:3:18) in
  node_modules/jws/lib/sign-stream.js
    at null.<anonymous> (index.js:12:50) in __require
    at null.<anonymous>
  (.../node_modules/jws/index.js:2:18) in
  node_modules/jws/index.js
    at null.<anonymous> (index.js:12:50) in __require
    at null.<anonymous>
  (.../node_modules/jsonwebtoken/decode.js:1:11) in
  node_modules/jsonwebtoken/decode.js
    at null.<anonymous> (index.js:12:50) in __require
    at null.<anonymous>
  (.../node_modules/jsonwebtoken/index.js:2:11) in
  node_modules/jsonwebtoken/index.js
   [code: 10021]
```

more context: [internal CF chat](https://chat.google.com/room/AAAAAPVuvtA/-jd-ZmmF-eA/KUYf6qEa1ws?cls=10)

**Comment by irvinebroque** [comment] 2024-06-12 00:49
@jasnell https://github.com/irvinebroque/node-util-repro

**Comment by WowVeryLogin** [comment] 2024-06-12 00:54
My worker code that reproduces the problem:
`
import jwt from "jsonwebtoken";
import JwkToPem from "jwk-to-pem";
import memoizer from "lru-memoizer";
import ms from "ms";

const client = memoizer({
  load: async (
    kid: string,
    callback: (err: Error | null, key: string | null) => string
  ) => {
    await fetch("https://api.cloudflare.com/client/v4/internal/certs")
      .then((r) => {
        return r.json();
      })
      .then((r) => {
        const resp = r as JWKSResponse;
        if (!resp.keys || !resp.keys.length) {
          return callback(new Error("no keys in JWKS endpoint response"), null);
        }

        const signingKey = resp.keys.find((key) => {
          return key.kid == kid;
        });

        if (!signingKey) {
          return callback(
            new Error("the JWKS endpoint did not contain any signing keys"),
            null
          );
        }

        return callback(null, JwkToPem(signingKey));
      });
  },
  hash: (kid) => kid,
  maxAge: ms("8h"),
  max: 4,
});

async function handleRequest(
  request: Request,
  env: Env,
  ctx: ExecutionContext
) {
  return new Response("", {
    status: 200
  });

export default {
  fetch: handleRequest,
};
`

**Comment by jasnell** [comment] 2024-06-12 01:42
Ok, quick investigation shows that the bug here is not in workerd or our Node.js built-ins. The issue is actually in the way wrangler is transforming the source internally. Specifically, the line that is blowing up is `util.inherits(DataStream, Stream)` in the `data-stream.js` file in the `jws` module. However, if you look at the way wrangler is transforming things, the line `const Stream = require('stream')`, which in Node.js and in Workerd returns the `Stream` class, the transpiled code is instead producing a copy of the module namespace object..

Specifically, in the transpile code, `Stream` ends up as...

```
{
  Duplex: [Getter],
  PassThrough: [Getter],
  Readable: [Getter],
  Stream: [Getter],
  Transform: [Getter],
  Writable: [Getter],
  _isUint8Array: [Getter],
  _uint8ArrayToBuffer: [Getter],
  addAbortSignal: [Getter],
  compose: [Getter],
  destroy: [Getter],
  finished: [Getter],
  isDisturbed: [Getter],
  isErrored: [Getter],
  isReadable: [Getter],
  pipeline: [Getter],
  promises: [Getter]
}
```

I would suspect that this is a limitation of the the transpiler that is being used.

**Comment by jasnell** [comment] 2024-06-13 15:06
Issue opened in workers-sdk. Closing this one.

**Closed by jasnell** 2024-06-13 15:06 UTC
Labels: frameworks

**Comment by IgorMinar** [comment] 2024-06-13 22:17
Thanks for looking into this @jasnell, let's continue the convo on the wrangler issue. Thanks for filing it!

**Comment by gerhardcit** [comment] 2024-11-08 12:49
FWIW: replacing jswebtoken with jose makes all these issues go away.
I dug through the _worker.js that sveltekit cloudflare adapter generates and found the require('node:buffer') in there which tripped me up.
