### ISSUE TITLE
🐛 Bug Report — D1 keeps crashing when working locally

### ISSUE THREAD

**Issue by xD0135** [cloudflare/workerd#1321] opened 2023-10-19 16:33 UTC
Hi 👋, I'm trying to run Workers with D1 locally but it always crashes with the following error:

```
workerd/util/symbolizer.c++:98: warning: Not symbolizing stack traces because $LLVM_SYMBOLIZER is not set. To symbolize stack traces, set $LLVM_SYMBOLIZER to the location of the llvm-symbolizer binary. When running tests under bazel, use `--test_env=LLVM_SYMBOLIZER=<path>`.
workerd/jsg/util.c++:275: error: e = workerd/util/sqlite.c++:386: failed: SQLite failed; sqlite3_errmsg(db) = database is locked;  sqlite3_prepare_v3(db, sqlCode.begin(), sqlCode.size(), prepFlags, &result, &tail)
stack: 107e0a936 107755765 107e19210 1079a4a2e 107479e9f 107479b11 1074798b8 107a2f448 107a2edce 107a02215 107a01bb8 107478ddd 107478467 107477f3e 10747d7be 10747d32b 107497599 107e02a70 107e03d7a 107a3b83d 1096ffb60 107bbb510; sentryErrorContext = jsgInternalError
[mf:err] Error: internal error
```
This happens with any operation that tries to interact with D1 locally as I'm following [D1's Get Started Guide](https://developers.cloudflare.com/d1/get-started/), such as this command for example:

```bash
wrangler d1 execute sample-db --local --file=./schema.sql
```
Even deleting the directory `.wrangler/state/v3/d1/miniflare-D1DatabaseObject` where the sqlite files are, and having D1 recreate it doesn't help. At this point I'm completely blocked from proceeding. 

My wranger.toml file is properly setup after executing the command to create the D1 database:

```bash
wrangler d1 create sample-db
```

```toml
name = "sample"
main = "src/index.ts"
compatibility_date = "2023-01-01"
send_metrics = false

[[d1_databases]]
binding = "DB"
database_name = "sample-db"
database_id = "REDACTED"
```

In order to confirm whether the issue was with my sqlite3 install, I wrote the following sample c++ program and it worked without issues:

```c++
// sample.cpp
#include <iostream>
#include <sqlite3.h>

int main(int argc, char** argv)
{
    sqlite3* DB;
    std::string stmt = "CREATE TABLE IF NOT EXISTS city(id INT PRIMARY KEY NOT NULL, name TEXT);";
    int exit = 0;
    exit = sqlite3_open("sample.db", &DB);
    if (exit != SQLITE_OK) {
        std::cerr << "Error creating database file" << std::endl;
        return exit;
    }

    char* errMsg;
    exit = sqlite3_exec(DB, stmt.c_str(), NULL, 0, &errMsg);
    if (exit != SQLITE_OK) {
        std::cerr << "Error creating table: " << errMsg << std::endl;
        sqlite3_free(errMsg);
        return exit;
    }

    sqlite3_close(DB);
    return exit;
}
```
Then compiling and running works as expected:
```bash
g++ sample.cpp -l sqlite3 -o sample-sqlite && ./sample-sqlite; echo $?
0
```

My environment is as follows:
- wrangler 3.13.1
- npm 10.2.0
- node v20.8.1
- macOS 13.6

I'm working on a time-sensitive project and would appreciate any help to unblock this issue. Thanks in advance.

**Comment by elithrar** [comment] 2023-10-19 22:38
Does this issue exhibit itself if you:

* delete the local database
* use a previous version of wrangler - e.g. 3.12.x - ?

**Comment by joshthoward** [comment] 2023-10-20 14:18
I cannot repro this. When you say you ran `wrangler d1 execute sample-db --local --file=./schema.sql` is `schema.sql` the same file that is linked in the getting started docs? 

It would really help if you could publish a git repo reproducing the problem.

**Comment by joshthoward** [comment] 2023-10-25 19:40
Hey @xD0135. I'm going to go ahead and close this issue because we cannot reproduce. Please reopen if you are able to publish a repro and we'll be happy to look into this.

**Closed by joshthoward** 2023-10-25 19:40 UTC
Labels: D1
