### ISSUE TITLE
`error: took recursive isolate lock; kj::getStackTrace()` on `storage.put`

### ISSUE THREAD

**Issue by broccolihighkicks** [cloudflare/workerd#706] opened 2023-05-24 19:29 UTC
I get this error:

```
workerd/jsg/jsg.c++:133: error: took recursive isolate lock; kj::getStackTrace() = 1004af23b 100750017 100772f97 100772f1b 101b9be03 1009e7e0b 10094f88f 10094fab7 101b6e68f 10083f98b 101b6e9b7 100840477 101b6e9b7 100735257 101b70337 101b6e9b7 100735e4b 101b6f663 101b6e68f 100736a7f 101b6e9b7 100736bab 101b6f663 101b6e68f 100736f8f 101b6e9b7 10073822f 101b6f663 101b6e68f
```

When doing multiple `storage.put` operations (in a Durable Object `alarm` - but I assume it happens in other places).

I am running my code with `wrangler dev src/index.ts --experimental-local`.

Versions:
`wrangler 2.17.0`

package-lock.json
```
"node_modules/workerd": {
    "version": "1.20230518.0",
    "resolved": "https://registry.npmjs.org/workerd/-/workerd-1.20230518.0.tgz",
    "integrity": "sha512-VNmK0zoNZXrwEEx77O/oQDVUzzyDjf5kKKK8bty+FmKCd5EQJCpqi8NlRKWLGMyyYrKm86MFz0kAsreTEs7HHA=="
},
```

[The workerd/jsg/jsg.c++:133 file mentions](https://github.com/cloudflare/workerd/blob/v1.20230518.0/src/workerd/jsg/jsg.c%2B%2B#LL133C3-L133C3):
` TODO(soon): This shouldn't happen but we know it does in at least one case.`

Do you know what I should do in my code to avoid this?

**Comment by AlCalzone** [comment] 2023-07-14 09:06
This happens for me on a Remix.run website for Cloudflare Pages, whenever I debug locally and open the website for the first time.

**Comment by AlCalzone** [comment] 2023-07-17 14:32
It does seem to work fine, but a full terminal page in red is a bit intimidating 😅

**Comment by kentonv** [comment] 2023-07-17 14:36
Yeah our logging in `workerd` is awkward now. In production, we convert these log lines into Sentry errors, and we tend to do a lot of logging that's just meant to be informative for us as the developers of workerd. For someone using workerd in their own infrastructure, the logging is not really appropriate. We need to figure out what to do about this but it's probably a big project...

**Comment by irvinebroque** [comment] 2023-07-18 03:57
If it's a warning, should [this](https://github.com/cloudflare/workerd/blob/v1.20230518.0/src/workerd/jsg/jsg.c%2B%2B#L133C5-L133C17) be `KJ_LOG(WARNING, ...)` instead of `ERROR`?

**Comment by oldben87** [comment] 2023-07-22 11:43
I'm seeing this error locally too. Not sure what it is I am doing to trigger it?

**Comment by Phoenixmatrix** [comment] 2023-09-18 02:44
Echoing the above, keep hitting this when using the wrangler pages runner. Its harmless, but it sure makes it tricky to see real errors, especially for newer devs in the team. Its a shame I have to tell people "just ignore the massive wall of red text..."

**Comment by aaronadamsCA** [comment] 2023-10-03 09:47
Note this seems to be the root cause of this pretty common frustration with Wrangler v3: https://github.com/cloudflare/workers-sdk/issues/3631

Wrangler v3 tries to print a stack trace to the console, but doesn't know how. Since that warning appears before this error, it's getting the bulk of the reports (including my original report).

So I think fixing this issue might also close that one.

**Comment by huw** [comment] 2023-11-26 11:31
I’ve submitted cloudflare/workers-sdk#4511 to use the new log suppression feature to also suppress these logs in `wrangler`, pending a fix for this underlying issue.

**Closed** 2023-12-14 11:33 UTC
